"""Initial lean persistence spine; frozen schema, not imports of future table definitions."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_lean_persistence"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("length(trim(project_id)) > 0", name=op.f("ck_projects_identity")),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_projects")),
    )
    op.create_table(
        "sources",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("display_observation_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_sources")),
    )
    op.create_table(
        "research_runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("request", sa.Text(), nullable=False),
        sa.Column("research_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'running' OR started_at IS NOT NULL", name=op.f("ck_research_runs_started")
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','completed','failed','cancelled')",
            name=op.f("ck_research_runs_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('completed','failed','cancelled') OR completed_at IS NOT NULL",
            name=op.f("ck_research_runs_completed"),
        ),
        sa.CheckConstraint("length(trim(request)) > 0", name=op.f("ck_research_runs_request")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
            name=op.f("fk_research_runs_project_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_research_runs")),
    )
    op.create_index("ix_research_runs_project", "research_runs", ["project_id"], unique=False)
    op.create_table(
        "source_documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("content_kind", sa.Text(), nullable=False),
        sa.Column("retrieval_context", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.CheckConstraint(
            "(content IS NULL AND content_sha256 IS NULL) OR (content IS NOT NULL AND "
            "content_sha256 = encode(sha256(content), 'hex'))",
            name=op.f("ck_source_documents_checksum"),
        ),
        sa.CheckConstraint(
            "status != 'usable' OR (content IS NOT NULL AND content_sha256 IS NOT NULL)",
            name=op.f("ck_source_documents_usable"),
        ),
        sa.CheckConstraint(
            "status IN ('usable','unavailable','failed','incomplete')",
            name=op.f("ck_source_documents_status"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_source_documents_source_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "document_id", "source_id", "status", name=op.f("uq_source_documents_document_id")
        ),
    )
    op.create_index(
        "ix_documents_source_time", "source_documents", ["source_id", "retrieved_at"], unique=False
    )
    op.create_index(
        "uq_document_version",
        "source_documents",
        ["source_id", "content_kind", "content_sha256"],
        unique=True,
        postgresql_where=sa.text("status = 'usable'"),
    )
    op.create_table(
        "source_identifiers",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('external_identifier','provider_record')",
            name=op.f("ck_source_identifiers_kind"),
        ),
        sa.CheckConstraint(
            "length(trim(namespace)) > 0 AND length(trim(value)) > 0",
            name=op.f("ck_source_identifiers_nonblank"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_source_identifiers_source_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("kind", "namespace", "value", name=op.f("pk_source_identifiers")),
    )
    op.create_index(
        "ix_source_identifiers_source", "source_identifiers", ["source_id"], unique=False
    )
    op.create_table(
        "extractions",
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("document_status", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("configuration_sha256", sa.Text(), nullable=False),
        sa.Column("configuration", sa.LargeBinary(), nullable=False),
        sa.Column("record_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("validation_outcome", sa.Text(), nullable=False),
        sa.Column("review_outcome", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publication_digest", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(status IN ('queued','running') AND completed_at IS NULL) OR (status NOT IN "
            "('queued','running') AND completed_at >= started_at)",
            name=op.f("ck_extractions_completion"),
        ),
        sa.CheckConstraint(
            "configuration_sha256 = encode(sha256(configuration), 'hex')",
            name=op.f("ck_extractions_configuration"),
        ),
        sa.CheckConstraint(
            "record_provenance->>'created_in_run_id' IS NOT NULL AND "
            "record_provenance->>'created_in_run_id' = run_id",
            name=op.f("ck_extractions_provenance"),
        ),
        sa.CheckConstraint(
            "review_outcome IN ('pending','accepted','rejected','not_required')",
            name=op.f("ck_extractions_review_outcome"),
        ),
        sa.CheckConstraint(
            "status != 'accepted' OR (document_status = 'usable' AND validation_outcome ="
            " 'passed' AND review_outcome IN ('accepted','not_required') AND "
            "publication_digest IS NOT NULL)",
            name=op.f("ck_extractions_accepted"),
        ),
        sa.CheckConstraint(
            "status = 'queued' OR started_at IS NOT NULL", name=op.f("ck_extractions_start")
        ),
        sa.CheckConstraint(
            "status IN ('queued','running') OR completed_at IS NOT NULL",
            name=op.f("ck_extractions_finalized"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','accepted','review_needed','failed','rejected')",
            name=op.f("ck_extractions_status"),
        ),
        sa.CheckConstraint(
            "validation_outcome IN ('pending','passed','failed')",
            name=op.f("ck_extractions_validation_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.run_id"],
            name=op.f("fk_extractions_run_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id", "source_id", "document_status"],
            [
                "source_documents.document_id",
                "source_documents.source_id",
                "source_documents.status",
            ],
            name=op.f("fk_extractions_source_document_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("extraction_id", name=op.f("pk_extractions")),
        sa.UniqueConstraint(
            "extraction_id", "source_id", "status", name=op.f("uq_extractions_extraction_id")
        ),
    )
    op.create_index("ix_extractions_document", "extractions", ["source_document_id"], unique=False)
    op.create_index("ix_extractions_run_status", "extractions", ["run_id", "status"], unique=False)
    op.create_table(
        "insights",
        sa.Column("insight_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("configuration_sha256", sa.Text(), nullable=False),
        sa.Column("record_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("qualifications", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "uncertainty_and_limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "generalizability_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "length(trim(claim)) > 0 AND configuration_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_insights_claim_configuration"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.run_id"],
            name=op.f("fk_insights_run_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("insight_id", name=op.f("pk_insights")),
    )
    op.create_index("ix_insights_run", "insights", ["run_id"], unique=False)
    op.create_table(
        "search_executions",
        sa.Column("search_execution_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("operation_id", sa.Text(), nullable=False),
        sa.Column("exact_query", sa.Text(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_limit", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("provider_result_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_batches", sa.Integer(), server_default="0", nullable=False),
        sa.Column("checkpoint", sa.Text(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "batch_receipts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(batch_receipts) = 'object' AND jsonb_typeof(parameters) = 'array'",
            name=op.f("ck_search_executions_json_shape"),
        ),
        sa.CheckConstraint(
            "status != 'failed' OR error_type IS NOT NULL",
            name=op.f("ck_search_executions_failure"),
        ),
        sa.CheckConstraint(
            "status != 'partial' OR checkpoint IS NOT NULL",
            name=op.f("ck_search_executions_partial"),
        ),
        sa.CheckConstraint(
            "status != 'succeeded' OR checkpoint IS NULL",
            name=op.f("ck_search_executions_exhaustion"),
        ),
        sa.CheckConstraint(
            "status = 'running' OR completed_at IS NOT NULL",
            name=op.f("ck_search_executions_completion"),
        ),
        sa.CheckConstraint(
            "status IN ('running','succeeded','partial','failed','cancelled')",
            name=op.f("ck_search_executions_status"),
        ),
        sa.CheckConstraint(
            "provider_result_count >= 0 AND completed_batches >= 0",
            name=op.f("ck_search_executions_counts"),
        ),
        sa.CheckConstraint(
            "requested_limit BETWEEN 1 AND 100", name=op.f("ck_search_executions_limit")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.run_id"],
            name=op.f("fk_search_executions_run_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("search_execution_id", name=op.f("pk_search_executions")),
        sa.UniqueConstraint(
            "search_execution_id", "run_id", name=op.f("uq_search_executions_search_execution_id")
        ),
    )
    op.create_index(
        "ix_search_executions_progress", "search_executions", ["run_id", "status"], unique=False
    )
    op.create_table(
        "run_sources",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("processing_state", sa.Text(), server_default="discovered", nullable=False),
        sa.Column("screening_decision", sa.Text(), nullable=True),
        sa.Column("screening_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "scoped_screening",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("selected_extraction_id", sa.UUID(), nullable=True),
        sa.Column(
            "selected_extraction_status", sa.Text(), server_default="accepted", nullable=False
        ),
        sa.CheckConstraint(
            "processing_state IN "
            "('discovered','retrieved','extracted','excluded','unavailable','failed')",
            name=op.f("ck_run_sources_processing_state"),
        ),
        sa.CheckConstraint(
            "screening_decision != 'exclude' OR processing_state = 'excluded'",
            name=op.f("ck_run_sources_exclusion"),
        ),
        sa.CheckConstraint(
            "screening_decision IN ('include','exclude','uncertain','defer','duplicate')",
            name=op.f("ck_run_sources_screening_decision"),
        ),
        sa.CheckConstraint(
            "selected_extraction_status = 'accepted'", name=op.f("ck_run_sources_selection")
        ),
        sa.CheckConstraint(
            "processing_state != 'extracted' OR selected_extraction_id IS NOT NULL",
            name=op.f("ck_run_sources_extracted"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.run_id"],
            name=op.f("fk_run_sources_run_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selected_extraction_id", "source_id", "selected_extraction_status"],
            ["extractions.extraction_id", "extractions.source_id", "extractions.status"],
            name=op.f("fk_run_sources_selected_extraction_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_run_sources_source_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", "source_id", name=op.f("pk_run_sources")),
    )
    op.create_index(
        "ix_run_sources_progress", "run_sources", ["run_id", "processing_state"], unique=False
    )
    op.create_index(
        "ix_run_sources_screening", "run_sources", ["run_id", "screening_decision"], unique=False
    )
    op.create_table(
        "source_metadata_observations",
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_record_id", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reported", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("search_execution_id", sa.Text(), nullable=False),
        sa.Column("input_batch_key", sa.Text(), nullable=False),
        sa.Column("page_position", sa.Integer(), nullable=False),
        sa.Column("conflict", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_source_metadata_observations_hash")
        ),
        sa.CheckConstraint(
            "page_position > 0 AND last_seen_at >= retrieved_at",
            name=op.f("ck_source_metadata_observations_position_time"),
        ),
        sa.CheckConstraint(
            "provider_record_id IS NULL OR length(trim(provider_record_id)) > 0",
            name=op.f("ck_source_metadata_observations_publication_id"),
        ),
        sa.ForeignKeyConstraint(
            ["search_execution_id"],
            ["search_executions.search_execution_id"],
            name=op.f("fk_source_metadata_observations_search_execution_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_source_metadata_observations_source_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_source_metadata_observations")),
        sa.UniqueConstraint(
            "observation_id",
            "source_id",
            name=op.f("uq_source_metadata_observations_observation_id"),
        ),
    )
    op.create_index(
        "ix_observations_source", "source_metadata_observations", ["source_id"], unique=False
    )
    op.create_index(
        "uq_observation_keyless_replay",
        "source_metadata_observations",
        ["search_execution_id", "input_batch_key", "page_position"],
        unique=True,
        postgresql_where=sa.text("provider_record_id IS NULL"),
    )
    op.create_index(
        "uq_observation_snapshot",
        "source_metadata_observations",
        ["provider", "provider_record_id", "content_hash"],
        unique=True,
        postgresql_where=sa.text("provider_record_id IS NOT NULL"),
    )
    op.create_table(
        "studies",
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("extraction_status", sa.Text(), server_default="accepted", nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("extraction_status = 'accepted'", name=op.f("ck_studies_accepted")),
        sa.ForeignKeyConstraint(
            ["extraction_id", "source_id", "extraction_status"],
            ["extractions.extraction_id", "extractions.source_id", "extractions.status"],
            name=op.f("fk_studies_extraction_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("study_id", name=op.f("pk_studies")),
    )
    op.create_index("ix_studies_extraction", "studies", ["extraction_id"], unique=False)
    op.create_index("ix_studies_source", "studies", ["source_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("anchors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(anchors) = 'array' AND jsonb_array_length(anchors) > 0",
            name=op.f("ck_findings_anchors"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.study_id"],
            name=op.f("fk_findings_study_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("finding_id", name=op.f("pk_findings")),
    )
    op.create_index("ix_findings_study", "findings", ["study_id"], unique=False)
    op.create_table(
        "source_discoveries",
        sa.Column("discovery_id", sa.Text(), nullable=False),
        sa.Column("search_execution_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_position", sa.Integer(), nullable=False),
        sa.Column("provider_record_id", sa.Text(), nullable=True),
        sa.CheckConstraint("result_position > 0", name=op.f("ck_source_discoveries_rank")),
        sa.ForeignKeyConstraint(
            ["observation_id", "source_id"],
            [
                "source_metadata_observations.observation_id",
                "source_metadata_observations.source_id",
            ],
            name=op.f("fk_source_discoveries_observation_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "source_id"],
            ["run_sources.run_id", "run_sources.source_id"],
            name=op.f("fk_source_discoveries_run_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["search_execution_id", "run_id"],
            ["search_executions.search_execution_id", "search_executions.run_id"],
            name=op.f("fk_source_discoveries_search_execution_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("discovery_id", name=op.f("pk_source_discoveries")),
        sa.UniqueConstraint(
            "search_execution_id",
            "source_id",
            name=op.f("uq_source_discoveries_search_execution_id"),
        ),
    )
    op.create_index("ix_discoveries_source", "source_discoveries", ["source_id"], unique=False)
    op.create_table(
        "insight_findings",
        sa.Column("insight_id", sa.UUID(), nullable=False),
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "relationship IN ('supporting','contradicting','contextual')",
            name=op.f("ck_insight_findings_relationship"),
        ),
        sa.CheckConstraint(
            "length(trim(rationale)) > 0", name=op.f("ck_insight_findings_rationale")
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.finding_id"],
            name=op.f("fk_insight_findings_finding_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.insight_id"],
            name=op.f("fk_insight_findings_insight_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("insight_id", "finding_id", name=op.f("pk_insight_findings")),
    )
    op.create_index("ix_insight_findings_finding", "insight_findings", ["finding_id"], unique=False)
    op.create_foreign_key(
        "fk_sources_display_observation",
        "sources",
        "source_metadata_observations",
        ["display_observation_id", "source_id"],
        ["observation_id", "source_id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    # ### end Alembic commands ###
    _immutability()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sources_display_observation", "sources", type_="foreignkey")
    op.drop_table("insight_findings")
    op.drop_table("source_discoveries")
    op.drop_table("findings")
    op.drop_table("studies")
    op.drop_table("source_metadata_observations")
    op.drop_table("run_sources")
    op.drop_table("search_executions")
    op.drop_table("insights")
    op.drop_table("extractions")
    op.drop_table("source_identifiers")
    op.drop_table("source_documents")
    op.drop_table("research_runs")
    op.drop_table("sources")
    op.drop_table("projects")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION atlas_immutable()")


def _immutability() -> None:
    op.execute("""
CREATE FUNCTION atlas_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME IN ('studies', 'findings') THEN
        RAISE EXCEPTION 'published evidence is immutable' USING ERRCODE = '23514';
    ELSIF TG_TABLE_NAME = 'source_documents' THEN
        IF OLD.status <> 'incomplete' THEN
            RAISE EXCEPTION 'finalized document is immutable' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'extractions' THEN
        IF OLD.status NOT IN ('queued', 'running') THEN
            RAISE EXCEPTION 'finalized extraction is immutable' USING ERRCODE = '23514';
        END IF;
        IF TG_OP = 'UPDATE' AND
            (NEW.run_id, NEW.source_document_id, NEW.purpose, NEW.configuration_sha256)
            IS DISTINCT FROM
            (OLD.run_id, OLD.source_document_id, OLD.purpose, OLD.configuration_sha256) THEN
            RAISE EXCEPTION 'extraction attempt identity is immutable' USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'source_metadata_observations' THEN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'metadata observations are retained' USING ERRCODE = '23514';
        END IF;
        IF (to_jsonb(NEW) - ARRAY['source_id', 'last_seen_at', 'conflict'])
           IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['source_id', 'last_seen_at', 'conflict'])
           OR (OLD.source_id IS NOT NULL AND NEW.source_id IS DISTINCT FROM OLD.source_id)
           OR NEW.last_seen_at < OLD.last_seen_at THEN
            RAISE EXCEPTION 'metadata snapshot is immutable' USING ERRCODE = '23514';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END; $$
""")
    for table in (
        "source_documents",
        "extractions",
        "studies",
        "findings",
        "source_metadata_observations",
    ):
        op.execute(
            f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION atlas_immutable()"
        )
